branch-defaults:
  master:
    environment: e-zvcgebsph9
global:
  application_name: http://samplenodejs-yukzeprzzt.elasticbeanstalk.com/
  default_platform: node.js
  default_region: us-west-2
  profile: eb-cli
  sc: git
