branch-defaults:
  master:
    environment: samplenodejsapp
    environment-id: e-xxztcyuzem
global:
  application_name: samplenodejsapp
  default_platform: node.js
  default_region: us-east-1
  profile: eb-cli
  sc: git
