branch-defaults:
  master:
    environment: nodeapp
    environment-id: e-dshccnksfu
    URL: nodeapp.bd4cre3cz3.us-east-1.elasticbeanstalk.com
global:
  application_name: nodeapp
  default_platform: node.js
  default_region: us-east-1
  profile: eb-cli
  sc: git
  
