branch-defaults:
  master:
    environment: Default-Environment
    environment-id: e-x3mqpdfrvr
    URL: Default-Environment.ppwmbw8cg9.us-east-1.elasticbeanstalk.com 
global:
  application_name: nodeapp
  default_platform: node.js
  default_region: us-east-1
  profile: eb-cli
  sc: git
 
